kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          resources:
             requests:
               memory: "64Mi"
               cpu: "250m"
             limits:
               memory: "128Mi"
               cpu: "500m"
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs.monitoring-pr
            - name: NFS_SERVER
              value: t4sto1000o-ora.hosts.eni.intranet
            - name: NFS_PATH
              value: /VK8SP/PR-MONITORING
          resources:
            requests:
               memory: 32Mi
               cpu: 50m
            limits:
               memory: 128Mi
               cpu: 100m
      volumes:
        - name: nfs-client-root
          nfs:
            server: t4sto1000o-ora.hosts.eni.intranet
            path: /VK8SP/PR-MONITORING

