apiVersion: v1
kind: Service
metadata:
  name: snmp-notifier
  namespace: monitoring
spec:
  selector: 
    app: snmp-notifier
  type: NodePort  
  ports:
    - port: 9464
      targetPort: 9464
      nodePort: 32500
