apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-notifier-configmap
  namespace: monitoring
data:
  WEB_LISTEN_ADDRESS: "9464"
  ALERT_SEVERITY_LABEL: severity
  ALERT_SEVERITIES: critical,warning,info
  ALERT_DEFAULT_SEVERITY: critical
  SNMP_VERSION: V2c
  SNMP_DESTINATION: t4srv100y0.ad04.eni.intranet:162
  SNMP_RETRIES: "1"
  SNMP_TRAP_OID_LABEL: oid
  SNMP_TRAP_DEFAULT_OID: 1.3.6.1.4.1.98789.0.1
  SNMP_TRAP_DESCRIPTION_TEMPLATE: /etc/snmp_notifier/description-template.tpl
  SNMP_EXTRA_FIELD_TEMPLATE: 4=new-field.template.tpl
  SNMP_TIMEOUT: 5s
  SNMP_COMMUNITY: public
  SNMP_AUTHENTICATION_ENABLED: "0"
  SNMP_AUTHENTICATION_PROTOCOL: MD5
  SNMP_AUTHENTICATION_USERNAME: username
  SNMP_AUTHENTICATION_PASSWORD: password
  SNMP_PRIVATE_ENABLED: "0"
  SNMP_PRIVATE_PROTOCOL: DES
  SNMP_PRIVATE_PASSWORD: secret
  SNMP_SECURITY_ENGINE_ID: XXXXX
  SMMP_CONTEXT_ENGINE_ID: YYYYY
  SNMP_CONTEXT_NAME: ZZZZZ
  LOG_LEVEL: debug
  LOG_FORMAT: logger:stderr

