kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: snmp-notifier
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: snmp-notifier
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: enits.project@dxc.com
        send_resolved: false
        from: k8s-svil@eni.com
        smarthost: relay.services.eni.intranet:25
        require_tls: false
    - name: snmp-notifier
      webhook_configs:
      - send_resolved: true
        url: http://t4srv100y0.ad04.eni.intranet:32500/alerts
        
