apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
  name: kubelet
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.59.112
        targetRef:
          kind: Node
          name: worker2
      - ip: 192.168.59.111
        targetRef:
          kind: Node
          name: worker1
    ports:
      - name: https-metrics
        port: 10250
        protocol: TCP
      - name: http-metrics
        port: 10255
        protocol: TCP
      - name: cadvisor
        port: 4194
        protocol: TCP
