apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-scheduler
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.59.100
        targetRef:
          kind: Node
          name: master
    ports:
      - name: https-metrics
        port: 10259
        protocol: TCP
