---
- hosts: "primary_master"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  

  tasks:
    - name: Include Variables
      ansible.builtin.include_vars:
        vars.yaml
  
    - name: Fecth joincluster-master.sh from remote
      become_user: "{{ansible_user}}"
      ansible.builtin.fetch:
        src: "{{ ansible_node_path }}/joincluster-master.sh"
        dest: "{{ ansible_controller_path }}/"
        flat: yes


    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - nfs-kernel-server

    - name: Get helm executable
      become_user: "{{ansible_user}}"
      ansible.builtin.get_url: 
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        mode: '0740'
        dest: "{{ansible_node_path}}/get_helm.sh"

    - name: Install helm
      become_user:
      ansible.builtin.shell:
        "{{ansible_node_path}}/get_helm.sh"

    
    - name: Fecth Kube config file
      become_user: "{{ansible_user}}"
      ansible.builtin.fetch:
        src: "{{ansible_node_path}}/.kube/config"
        dest: "{{ansible_controller_root_path}}/.kube/"
        flat: yes