apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ephemeralpods.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: Ephemeralpod
    plural: ephemeralpods
    singular: ephemeralpod
    shortNames:
      - epod
      - epods
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
