apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{name}"
  labels:
    epod: "{label}"
  # annotations:
  #   volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName:  "{storageClassName}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{size}"