apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sa_name }}
  # replace with namespace where provisioner is deployed
  namespace: {{ .Values.namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole_name}}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolebinding_name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sa_name }}
    # replace with namespace where provisioner is deployed
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrole_name }}
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.role_name }}
  # replace with namespace where provisioner is deployed
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rolebinding_name }}
  # replace with namespace where provisioner is deployed
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sa_name}}
    # replace with namespace where provisioner is deployed
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.role_name }}
  apiGroup: rbac.authorization.k8s.io
